### ISSUE TITLE
MorfFlex nekonzistence (hnát)

### ISSUE THREAD

**Issue by martinpopel** [ufal/PDT-C#6]
Při výuce jsme teď se Zdeňkem (@zabokrtsky) narazili na to, že MorfFlex vrací pro "hnát" tři slovesná lemmata:

* `hnát-1_^(tvar_slovesa;_[utíkat])`
* `hnát-1_:T_^(tvar_slovesa;_[utíkat])` (jen přechodníkové tvary)
* `hnát_^(tvar_slovesa;_[utíkat])` (jen tvary "nehnat", "nehnati")

Tomu nerozumím. Řekl bych, že by mělo být jen jedno lemma (asi to první). Tipuji to na nějaký relikt z minulých verzí.

Postup: na http://lindat.mff.cuni.cz/services/morphodita/ vyberu "czech-morfflex-pdf-161115" a "Generate" a do Input text zadám "hnát".
Přitom pro "Analyze" mi to vrátí jen to první lemma.

Nevím, kam se mají hlásit takovéto chyby/nekonzistence MorfFlexu (@hlavacova). Na https://ufal.mff.cuni.cz/morfflex se píše "MorfFlex CZ 2.0 is an integral part of the PDT-C 1.0 release.", tak to hlásím zde. Osobně to nepotřebuju opravit, jen poskytuji zpětnou vazbu (pokud se o tom náhodou neví).

**Comment by hlavacova** [comment]
Ahoj Martine,
chyby určitě hlásit, určitě )(i) mně .
Než chybu nahlásíte, můžete (nemusíte) si zkontrolovat, zda už to není vyřešené, zde:
http://quest.ms.mff.cuni.cz/~straka/morphodita-pdt-c/
Je možné i přepínat mezi 3 modely.
Zatím je to jen interní.
Jarka

----- Original Message -----

**Comment by hlavacova** [comment]
Ještě jsem zapomněla dodat, že je to tak, jak píšeš, že by to mělo být :-)
Jarka

----- Original Message -----
